const LANGS = {
es: {
nav_park:"Estacionar", nav_health:"Salud", nav_security:"Seguridad",
nav_commerce:"Servicios", nav_pottery:"Alfarería", nav_food:"Comer",
nav_around:"Alrededores", nav_shops_g:"Comercio", nav_plaza:"Plaza Pública", nav_map:"Mapa", nav_donate:"Apoyar", nav_tagline:"Turismo & Cultura",
hero_tag:"📍 Pomaire · Melipilla · Región Metropolitana",
hero_h1:"Bienvenido a <em>Pomaire</em>",
hero_sub:"Todo lo que necesitas saber si estás de visita o acabas de llegar al pueblo alfarero más famoso de Chile. Servicios, emergencias, estacionamientos y mucho más.",
cta_plan:"Planifica tu visita", cta_directions:"Cómo llegar", cta_eat:"Directorio de Negocios",
wa_text:"Compartir", wa_aria:"Compartir Pomaire 360 por WhatsApp",
wa_share:"¡Descubre Pomaire, el pueblo alfarero más famoso de Chile! 🏺 Guía completa de servicios, gastronomía y turismo: https://www.pomaire360.cl/",
emer_police:"🚔 133 Carabineros", emer_samu:"🚑 131 SAMU Ambulancia", emer_fire:"🚒 132 Bomberos", emer_peace:"🕊️ 149 Paz ciudadana",
s_park_title:"Estacionamientos", s_park_sub:"Llegan miles de visitantes cada fin de semana — planifica dónde dejar tu auto",
s_health_title:"Salud y urgencias médicas", s_health_sub:"CESFAM, hospital y SAMU para Pomaire y alrededores",
s_sec_title:"Seguridad y emergencias", s_sec_sub:"Carabineros, Bomberos y líneas de apoyo",
s_com_title:"Almacenes y servicios cotidianos", s_com_sub:"Lo básico para vivir o pasar el día en Pomaire",
s_pot_title:"Alfarería — el corazón de Pomaire", s_pot_sub:"Talleres, compras y la tradición artesanal que define al pueblo",
s_gas_title:"Gastronomía típica", s_gas_sub:"Sabores tradicionales en cazuela de greda",
s_aro_title:"Alrededores de Pomaire", s_aro_sub:"Los Chiñihues y sectores cercanos que vale la pena conocer",
s_pla_title:"Plaza y espacios públicos", s_pla_sub:"Puntos de encuentro y descanso en el corazón de Pomaire",
s_map_title:"Pomaire en el mapa", s_map_sub:"Ubicación del pueblo y sus alrededores",
s_don_title:"Apoya este proyecto", s_don_sub:"Guía gratuita, mantenida con voluntad y amor por Pomaire",
donate_text:"Pomaire 360 es un proyecto independiente sin publicidad. Si te fue útil esta guía, un aporte voluntario ayuda a mantener la información actualizada. ¡Gracias!",
donate_btn:"🏺 Hacer un aporte voluntario",
donate_note:"Pago seguro con Mercado Pago · tarjeta, transferencia o billetera digital",
emer_numbers:"Números de emergencia",
footer_tagline:"Guía para visitantes y nuevos residentes",
footer_emer:"Emergencias:",
footer_disc:"Información de carácter orientativo. Verifica horarios y datos directamente con cada institución.",
footer_date:"Última revisión: junio 2026 · Pomaire, Melipilla, Región Metropolitana",
nav_weather:"Clima", nav_tour:"Recorrido", nav_gallery:"Galería", nav_events:"Eventos", nav_advertise:"Anúnciate", nav_suggest:"Sugerencias",
s_weather_title:"Clima en Pomaire ahora", s_weather_sub:"Condiciones actuales para planificar tu visita",
weather_note:"Datos en tiempo real · Open-Meteo · Coordenadas Pomaire",
s_tour_title:"Recorrido turístico paso a paso", s_tour_sub:"La ruta perfecta para aprovechar tu día en Pomaire",
tour_1_title:"Llegada y estacionamiento", tour_1_desc:"Llega antes de las 10:00 para conseguir estacionamiento en calle Rafael Morandé.",
tour_2_title:"Desayuno en la plaza", tour_2_desc:"Toma un café o desayuno liviano en algún local de la plaza central.",
tour_3_title:"Recorre los talleres alfareros", tour_3_desc:"Camina por la calle principal y entra a los talleres. Mira a los artesanos trabajar en el torno.",
tour_4_title:"Compras de artesanía", tour_4_desc:"Compra directamente a los artesanos. Jarras, cazuelas, tinajas y el famoso chanchito alcancía.",
tour_5_title:"Almuerzo típico", tour_5_desc:"Disfruta una cazuela de vacuno o empanada gigante servida en recipiente de greda.",
tour_6_title:"Paseo por los alrededores", tour_6_desc:"Date una vuelta por Los Chiñihues. Paisaje rural y tranquilidad a pocos minutos.",
tour_7_title:"Regreso con recuerdos", tour_7_desc:"Última vuelta por los puestos. Muchos artesanos hacen descuentos al final del día.",
s_gallery_title:"Galería de Pomaire", s_gallery_sub:"Imágenes del pueblo alfarero y sus tradiciones",
gal_1:"Alfarería en greda", gal_2:"Cazuela de barro", gal_3:"Los Chiñihues",
gal_4:"Calle principal", gal_5:"Artesanos trabajando", gal_6:"Iglesia San Antonio",
gallery_note:"📷 ¿Visitaste Pomaire? Comparte tus fotos etiquetando #Pomaire360",
s_events_title:"Eventos y fechas importantes", s_events_sub:"Festividades, ferias y celebraciones en Pomaire",
ev_1_title:"Temporada alta de verano", ev_1_desc:"Mayor afluencia de turistas nacionales. Llegar temprano es clave.",
ev_2_title:"Fiesta de San Antonio de Padua", ev_2_desc:"Festividad religiosa patronal. Procesión, actividades culturales y gastronomía especial.",
ev_3_title:"Fiestas Patrias", ev_3_desc:"18 de septiembre — fondas, chicha artesanal, cueca y artesanía festiva.",
ev_4_title:"Feria de artesanía navideña", ev_4_desc:"Nacimientos en greda, adornos y regalos únicos hechos a mano.",
ev_tag_busy:"Alta demanda", ev_tag_fest:"Fiesta patronal", ev_tag_nat:"Fiestas patrias", ev_tag_xmas:"Navidad",
ev_m5:"OCT", ev_5_desc:"Celebración anual de la tradición alfarera de Pomaire: demostraciones de artesanos, venta de artesanía, gastronomía típica y actividades culturales para toda la familia.",
eb_kicker:"🎉 Qué está pasando en Pomaire", eb_title:"Próximos eventos y festividades", eb_sub:"Ferias, fiestas y celebraciones del pueblo alfarero. Toca un evento para ver todos los detalles.",
eb_go:"Ver detalles →", eb_all:"Ver el calendario completo de eventos →",
eb_2_teaser:"Procesión, actividades culturales y gastronomía especial en la plaza.",
eb_3_teaser:"Fondas, chicha artesanal, cueca y artesanía festiva. ¡La mejor época!",
eb_4_teaser:"Nacimientos en greda, adornos y regalos únicos hechos a mano.",
eb_greda_title:"Fiestas de la Greda", eb_greda_teaser:"Demostraciones de artesanos, venta de greda y actividades para toda la familia.", eb_tag_greda:"Tradición alfarera",
eb_empanada_title:"Concurso de la Mejor Empanada de Pomaire", eb_empanada_teaser:"Horno de barro, jurado popular y las míticas empanadas gigantes. ¡Gracias a todos por participar!", eb_tag_food:"Evento gastronómico", eb_flag_new:"¡Nuevo!", eb_flag_soon:"✅ FINALIZADO",
eb_mon_jun:"JUN", eb_mon_sep:"SEP", eb_mon_oct:"OCT", eb_mon_nov:"NOV", eb_mon_novdic:"NOV–DIC",
filter_all:"Todos", filter_parking:"Estacionar", filter_health:"Salud", filter_security:"Seguridad",
filter_pottery:"Alfarería", filter_food:"Comer", filter_services:"Servicios", filter_around:"Alrededores",
locate_btn:"Usar mi ubicación", map_hint:"📍 Activa tu ubicación o haz clic en un punto de partida en el mapa para calcular distancias",
official_map_btn:"Ver mapa oficial ilustrado de Pomaire", official_map_note:"Plano turístico oficial con el directorio numerado de talleres de artesanos.", official_map_dl:"Descargar mapa",
routes_title:"🧭 Recorridos sugeridos",
route_artisan_name:"Ruta del Artesano", route_artisan_meta:"3 paradas · ~1.5 hrs",
route_family_name:"Ruta Familiar", route_family_meta:"4 paradas · ~2.5 hrs",
route_food_name:"Ruta Gastronómica", route_food_meta:"3 paradas · ~1 hr",
route_nature_name:"Ruta Naturaleza", route_nature_meta:"3 paradas · ~3 hrs",
route_clear:"Quitar ruta",
chapter_explore:"Capítulo 1 — Explora el pueblo",
chapter_plan:"Capítulo 2 — Planifica tu ruta",
chapter_prepare:"Capítulo 3 — Prepárate para el viaje",
chapter_remember:"Capítulo 4 — Llévate un recuerdo",
chapter_comeback:"Capítulo 5 — Planifica tu regreso",
hero_scroll:"Descubre",
nav_map_full:"Mapa Turístico",
nav_g_essentials:"Esenciales",
nav_g_todo:"Qué hacer",
nav_g_eatsleep:"Comer y dormir",
nav_g_plan:"Planifica",
footer_explore:"Explorar",
footer_services:"Servicios",
footer_merchants:"Para comerciantes",
footer_community:"Comunidad",
gf_cta:"¡Juega!",
an_cta:"Agregar tu negocio",
fpb_tag:"💎 Imperdible",
fpb_text:"El chancho alcancía de greda <strong>más grande del mundo</strong>",
fpb_cta:"Conócelo →",
map_full_cta:"Abrir Mapa Turístico completo",
map_full_cta_note:"Vista ampliada con leyenda, estilos de mapa, compartir lugares y más",
search_empty:"No se encontraron resultados",
search_placeholder:"Buscar en Pomaire 360...",
gal_7:"Chancho alcancía gigante",
gal_8:"Entrada a Pomaire",
gal_9:"Calle de la artesanía",
gal_10:"Pomaire histórico",
gal_11:"Valle al atardecer",
gal_12:"Ollas chanchito de greda",
gal_13:"Figuras de greda tradicionales",
filter_lodging:"Dormir",
filter_highlight:"Qué ver",
ev_m1:"ENE–FEB", ev_m2:"JUN", ev_m3:"SEP", ev_m4:"NOV–DIC"
},
};
let currentLang = 'es';
Object.assign(LANGS.es, {
nav_lodging:"Alojamientos", nav_banos:"Baños", nav_seewhat:"Qué ver",
nav_g_essentials:"Esenciales", nav_g_todo:"Qué hacer", nav_g_eatsleep:"Comer y dormir", nav_g_plan:"Planifica", nav_winery:"Ruta del Vino", site_municipality:"Municipalidad", site_official_map:"Ver mapa oficial de Pomaire",
ev_m1:"ENE–FEB", ev_m2:"JUN", ev_m3:"SEP", ev_m4:"NOV–DIC", weather_loading:"⏳ Cargando clima...", social_title:"Síguenos en redes", social_sub:"Fotos, novedades y la vida del pueblo alfarero, todos los días.", social_ig:"Síguenos en Instagram",
a11y_title:"♿ Accesibilidad", a11y_font:"🔠 Tamaño de letra", a11y_read:"🔊 Lectura en voz alta", a11y_readall:"📖 Leer todo", a11y_hint:"Activa la lectura y luego toca cualquier texto del sitio para escucharlo en voz alta.", a11y_hint_active:"✅ Lectura activa: toca cualquier texto del sitio para escucharlo.", a11y_activate:"🔊 Activar", a11y_stop:"⏹ Detener", a11y_unavailable:"🔇 No disponible", a11y_size_normal:"Tamaño normal", a11y_size:"Tamaño", a11y_voice_on:"Lectura en voz alta activada. Toca cualquier texto para escucharlo.", a11y_no_support:"Tu navegador no soporta la lectura en voz alta.", a11y_aria_options:"Opciones de accesibilidad", a11y_aria_close:"Cerrar",
s_lodging_title:"Alojamientos", s_lodging_sub:"Hostales, cabañas y suites para quedarte en Pomaire · <em>Where to stay</em>",
s_interes_title:"Qué ver y puntos de interés", s_interes_sub:"Atractivos, tiendas con encanto y experiencias al paso · <em>Highlights &amp; things to see</em>",
lnk_map:"📍 Ver en mapa", lnk_zone:"📍 Ver zona", lnk_howto:"📍 Cómo llegar",
pk1_badge:"Principal · Entrada norte", pk1_title:"Estacionamiento Entrada Pomaire", pk1_detail:"Calle Rafael Morandé, frente al acceso principal. El más grande del pueblo. Fin de semana puede llenarse antes de las 11:00.",
pk2_badge:"Lateral · Calle artesanos", pk2_title:"Estacionamiento Calle 18 de Septiembre", pk2_detail:"Banquinas en calle 18 de Septiembre, lateral al casco principal. Opción si la entrada norte está llena.",
pk3_badge:"Buses y minibuses", pk3_title:"Zona de buses turísticos", pk3_detail:"Sector habilitado para buses y furgones de turismo. Pregunta al guardia en la entrada norte.",
pk4_badge:"Consejo", pk4_title:"Tips para estacionar", pk4_detail:"Llegando antes de las 10:30 en fines de semana evitas la saturación. No bloquees salidas de vecinos ni caminos rurales.",
he1_badge:"CESFAM · Pomaire", he1_detail:"Artesana Julita Vera 354, Pomaire",
he2_badge:"Hospital · Melipilla", he2_detail:"O'Higgins 551, Melipilla · Urgencias 24 hrs. Referencia principal para casos graves desde Pomaire (≈15 min en auto).",
he3_badge:"Emergencia · 24 hrs", he3_title:"SAMU Ambulancia — emergencias", he3_detail:"Llamada gratuita desde cualquier teléfono, las 24 horas. Para accidentes, infarto, urgencias vitales.", he3_link:"📞 Llamar 131",
he4_badge:"Farmacia · Melipilla", he4_title:"Farmacias en Melipilla", he4_detail:"En Pomaire existe una farmacia. Dirección San Antonio 140. Farmacias de Turno diario rotativo.", he4_link:"🔗 Ver turno hoy",
emn_police:"Carabineros", emn_samu:"SAMU Ambulancia", emn_fire:"Bomberos", emn_peace:"Paz ciudadana", emn_vif:"VIF · Mujer", emn_power:"Corte luz CGE",
se1_badge:"Carabineros · Pomaire", se1_title:"Tenencia Pomaire", se1_detail:"Calle San Rafael 496. Atención local de Policia Carabineros.", se_emer133:"📞 Emergencias 133", se1_link2:"📞 Emergencias Plan Cuadrante +56984289058",
se2_badge:"Bomberos · Melipilla", se2_title:"Central de Bomberos Melipilla", se2_detail:"Responden para Pomaire y localidades rurales. Ante incendio o rescate llama al 132.", se_emer132:"📞 Emergencias 132",
se3_badge:"Servicio eléctrico", se3_title:"CGE — Corte de luz", se3_detail:"Para reportar averías eléctricas domiciliarias. Disponible las 24 horas.",
co1_badge:"Almacén · Centro", co1_title:"Almacenes en calle principal", co1_detail:"Varios almacenes y minimarkets en Rafael Morandé y alrededores. Venden agua, snacks, artículos básicos para el visitante.",
co2_badge:"Mecánico · Ruta", co2_title:"Mecánico / Taller automotriz", co2_detail:"Hay pequeños talleres en la ruta de acceso y en el camino hacia Melipilla. Para averías graves lo más cercano está en Melipilla ciudad.", co2_link:"📍 Buscar talleres",
co3_badge:"Combustible", co3_title:"Bencinerías", co3_detail:"La bencinería más cercana está en la ruta hacia Melipilla. Se recomienda llegar con el estanque lleno si vienes de Santiago.",
co4_badge:"Cajero · Efectivo", co4_title:"Cajeros automáticos", co4_detail:"hay un cajero automático dentro del pueblo Calle Roberto Bravo 445. Muchos locales aceptan tarjeta.",
co5_badge:"Correos / Encomiendas", co5_title:"Correos Chile", co5_detail:"La oficina de Correos más cercana está en Melipilla ciudad. Coordina despachos desde allí.",
co6_badge:"Información turística", co6_title:"Punto de información local", co6_detail:"En la entrada principal hay señalética turística. Los artesanos y locatarios suelen orientar bien a los visitantes.", co6_detail2:"En la plaza de Pomaire existe un punto de información turistica.",
shops_all_h:"Todas las tiendas de Pomaire", shops_all_sub:"Explora el comercio local por categoría: alfarería, gastronomía, boutiques, alojamiento y jardinería",
tab_pottery:"Alfarería y cerámica", tab_pottery_sub:"Compra directamente al artesano · listado completo de alfareros de Pomaire",
tab_food:"Restaurantes", tab_food_sub:"Restaurantes de Pomaire con dirección, teléfono y días de atención",
tab_boutique:"Tiendas y boutiques", tab_boutique_sub:"Ropa, cecinas, cerveza artesanal, bienestar y otros comercios con encanto",
tab_lodging:"Alojamientos", tab_lodging_sub:"Hostales, cabañas y suites para quedarte en Pomaire",
tab_garden:"Jardinería",
pl1_badge:"Plaza · Centro", pl1_title:"Plaza de Pomaire", pl1_detail:"La plaza central es el corazón del pueblo. Rodeada de locales de artesanía y gastronomía. Ideal para descansar y orientarse.",
pl2_badge:"Iglesia", pl2_detail:"Iglesia histórica del pueblo. Referente arquitectónico.",
pl3_badge:"Salón del Reino", pl3_detail:"Espacio Público Espiritual. Horarios: Jueves 19:00 - 21:15 hrs. Sábado 19:00-20:45 Hrs..",
pl4_badge:"Servicios", pl4_title:"Baños públicos", pl4_detail:"Hay baños disponibles cerca de la plaza central y en algunos locales gastronómicos. En temporada alta puede haber cola.",
al1_badge:"Artesanía · Calle principal", al1_title:"Calle de los alfareros", al1_detail:"Rafael Morandé es la calle principal, repleta de talleres y tiendas donde artesanos trabajan y venden en vivo. Piezas en greda: jarras, cazuelas, tinajas y más.",
al2_badge:"Taller abierto", al2_title:"Ver alfareros trabajando", al2_detail:"Muchos artesanos trabajan con sus tornos y hornos a la vista. Se puede ver el proceso completo: desde la greda cruda hasta la pieza terminada.",
al3_badge:"Consejos de compra", al3_title:"Comprar artesanía responsable", al3_detail:"Prefiere comprar directamente al artesano. Evita regatear agresivamente — cada pieza tiene trabajo y tradición familiar detrás.",
al4_badge:"Patrimonio", al4_title:"Patrimonio inmaterial de Chile", al4_detail:"La alfarería de Pomaire es reconocida como patrimonio cultural. Técnicas transmitidas de generación en generación por siglos.",
al5_badge:"Chanco Alcancia", al5_title:"Chancho Alcancia de greda más grande del mundo", al5_detail:"Museo con figuras de greda gigantes",
dir_taller_h:"🎨 Talleres de greda", dir_taller_sub:"Aprende a modelar la greda con artesanos pomairinos · <em>Pottery workshops</em>",
dir_demo_h:"🌀 Demostraciones en torno", dir_demo_sub:"Mira a los maestros dar forma a la greda en vivo · <em>Pottery wheel demonstrations</em>",
dir_arte_h:"🏺 Tiendas y artesanos de greda", dir_arte_sub:"Compra directamente al artesano. Listado completo de alfareros de Pomaire · <em>Pottery shops &amp; artisans</em>",
ga1_badge:"Plato estrella", ga1_title:"Cazuela de barro", ga1_detail:"El plato más icónico de Pomaire. Cazuelas, empanadas y pastel de choclo servidos en recipientes de greda fabricados en el propio pueblo.",
ga2_badge:"Clásico", ga2_title:"Empanadas gigantes", ga2_detail:"Pomaire es famoso por sus empanadas de gran tamaño. Hay locales de empanadas a lo largo de toda la calle principal.",
ga3_badge:"Bebidas", ga3_title:"Chicha y bebidas tradicionales", ga3_detail:"Chicha de manzana y uva, mote con huesillo y bebidas artesanales. Perfectos para acompañar la gastronomía local.",
ga4_badge:"Dónde comer", ga4_title:"Restaurantes y fondas", ga4_detail:"Numerosos restaurantes en la calle principal y sus laterales. Los fines de semana pueden tener espera. Se recomienda llegar antes del mediodía.", ga4_link:"📋 Ver directorio", ga4_map:"🗺️ Ver en el mapa",
dir_rest_h:"🍴 Directorio de restaurantes", dir_rest_sub:"Restaurantes de Pomaire con dirección, teléfono y días de atención · <em>Restaurants directory</em>",
lodging_note:"💡 Quedarte a dormir te permite disfrutar Pomaire sin la multitud de los buses de turismo y vivir el pueblo de noche.",
dir_jardin_h:"🌱 Jardinería y viveros", dir_jardin_sub:"Plantas, flores y un respiro verde · <em>Gardening &amp; plants</em>",
dir_serv_h:"📌 Puntos clave y servicios", dir_serv_sub:"Ubicaciones útiles durante tu visita · <em>Key points &amp; services</em>",
ar1_badge:"Sector rural · Cercano", ar1_detail:"Localidad rural muy cercana a Pomaire. Paisaje de secano costero con viñedos y quebradas. Ideal para quienes buscan tranquilidad y naturaleza fuera del casco turístico.",
ar2_badge:"Rutas rurales", ar2_title:"Caminos y vinos del secano", ar2_detail:"El entorno de Pomaire es zona vitivinícola tradicional. Pequeños productores familiares de chicha y vino en el sector de Los Chiñihues y caminos aledaños.",
ar3_badge:"Naturaleza", ar3_title:"Cerros y quebradas", ar3_detail:"Los cerros que rodean Pomaire ofrecen vistas al valle de Melipilla. Hay senderos informales accesibles desde la ruta que une el pueblo con Los Chiñihues.",
ar4_badge:"Acceso", ar4_title:"Cómo llegar desde Santiago", ar4_detail:"Autopista del Sol (Ruta 78) hacia Melipilla. Salida en el km 51 con señalética a Pomaire. Aproximadamente 50 min desde Santiago en auto.",
ar5_badge:"Transporte público", ar5_title:"Buses desde Santiago/Melipilla", ar5_detail:"Hay buses desde el Terminal San Borja (Santiago) con parada en Melipilla. Desde Melipilla salen micros rurales hacia Pomaire regularmente.", ar5_link:"📍 Terminal Melipilla",
ar6_badge:"Conectividad", ar6_title:"Señal móvil y WiFi", ar6_detail:"La señal celular en Pomaire es razonable en el centro, pero puede ser débil en Los Chiñihues y sectores rurales. Algunos restaurantes ofrecen WiFi.",
wine_title:"Ruta del Vino y la Chicha", wine_sub:"El secano costero de Pomaire y Los Chiñihues, tierra de viñas tradicionales · <em>Wine &amp; chicha route</em>",
wine_tag:"🍇 Experiencia · Valle de Melipilla · Secano Costero",
wine_intro:"Más allá de la greda, el entorno de Pomaire es <strong>tierra de viñas y parras tradicionales</strong>. En el secano costero y el sector de <strong>Los Chiñihues</strong> sobreviven pequeños productores familiares que elaboran <strong>chicha de manzana y uva</strong>, pipeño y vino campesino con técnicas heredadas por generaciones. Una ruta para descubrir el lado rural y festivo del pueblo alfarero.",
wine_c1_t:"Cepa País", wine_c1_d:"La uva tradicional del secano chileno, base de los vinos campesinos y del pipeño. Una de las cepas más antiguas del país, cultivada en parronales rústicos de la zona.",
wine_c2_t:"Chicha artesanal", wine_c2_d:"La bebida emblemática del lugar: chicha de manzana y de uva, fresca y dulce. Se encuentra en los restaurantes típicos y abunda especialmente en torno a las Fiestas Patrias.",
wine_c3_t:"Pipeño del secano", wine_c3_d:"Vino joven y rústico, de carácter campesino, ideal para acompañar una cazuela o una empanada gigante. El maridaje perfecto de la cocina pomairina.",
wine_c4_t:"Los Chiñihues", wine_c4_d:"Sector rural a pocos minutos de Pomaire, de viñedos, quebradas y caminos tranquilos. El corazón de la tradición vitivinícola familiar de los alrededores.",
wine_c5_t:"Maridaje en greda", wine_c5_d:"La chicha y el vino se sirven en jarras y vasijas de greda hechas en el propio pueblo, uniendo en una sola experiencia las dos grandes tradiciones de Pomaire.",
wine_c6_t:"Mejor temporada", wine_c6_d:"La vendimia (marzo–abril) y las Fiestas Patrias (septiembre) son las épocas con más chicha fresca, parras cargadas y ambiente festivo en el secano.",
wine_steps_h:"🧭 Cómo recorrer la ruta",
wine_s1_t:"Parte en el centro de Pomaire", wine_s1_d:"Prueba una chicha de manzana o uva en los restaurantes típicos de la calle Roberto Bravo y San Antonio.",
wine_s2_t:"Sigue hacia Los Chiñihues", wine_s2_d:"Recorre en auto los caminos rurales del secano, entre parronales y quebradas. Lleva el estanque lleno: hay poca señal y pocos servicios.",
wine_s3_t:"Busca a los productores familiares", wine_s3_d:"Pregunta en el pueblo por chicha y vino artesanal de temporada; muchos se venden directamente en casas y puestos del sector.",
wine_s4_t:"Cierra con gastronomía", wine_s4_d:"Vuelve al pueblo y marida tu hallazgo con una cazuela o empanada servida en greda. ¡Salud!",
wine_cta_t:"🍷 ¿Tienes una viña, parronal o produces chicha en la zona? Suma tu lugar a esta ruta y aparece en la guía.", wine_cta_btn:"🗺️ Ver Los Chiñihues",
wine_note:"Ruta basada en la tradición vitivinícola del secano costero de Melipilla. Los productores y horarios varían según la temporada; consulta en el pueblo. Bebe con moderación · solo mayores de 18 años.",
or_title:"Ruta Turística Oficial de Pomaire", or_src:"Itinerario sugerido por la Oficina de Turismo · Municipalidad de Melipilla · <em>Official tourist route</em>",
or_badge1:"🚶 Recorrido a pie: ~35 min", or_badge2:"🚗 Recorrido en auto: ~19 min", or_badge3:"📅 Día completo desde Santiago",
or_st1_t:"Salida desde Santiago", or_st1_d:"Inicio del viaje hacia el pueblo alfarero.",
or_st2_t:"Llegada a Pomaire", or_st2_d:"Recibimiento en la Oficina de Información Turística (OIT), en la Plaza de Pomaire.",
or_st3_t:"Desayuno en Imperio Pomaire", or_st3_d:"Roberto Bravo 78 · Sabores típicos chilenos para comenzar el día.",
or_st4_t:"Taller de greda en la Granja Alfarera", or_st4_d:"Bernardo O'Higgins 260 · Experiencia inmersiva: del torno al horno.",
or_st5_t:"Almuerzo en Restaurant La Greda", or_st5_d:"Cocina criolla y parrilla chilena con más de 30 años de historia.",
or_st6_t:"Visita al Vivero Luchín", or_st6_d:"San Antonio 191 · Un respiro verde entre plantas, flores y maceteros.",
or_st7_t:"Tarde libre de compras", or_st7_d:"Recorre los talleres y tiendas de greda de la calle Roberto Bravo.",
or_st8_t:"Retorno a Santiago", or_st8_d:"Fin del recorrido con recuerdos hechos a mano.",
or_f1:"Nacido del esfuerzo de Romina y Fabio por la cocina tradicional. Tras siete años abrieron un segundo local y hoy es un referente de los sabores típicos de Pomaire.",
or_f2:"Espacio turístico-cultural dedicado a preservar el oficio de la greda. Ofrece demostraciones en vivo, talleres con artesanos pomairinos y un recorrido por todo el proceso, desde la extracción hasta el horno.",
or_f3:"Más de 30 años de tradición. Don Víctor Larraín transformó la antigua casona de adobe familiar en un referente gastronómico, cuna de la empanada más grande del mundo y de tres generaciones de cocina criolla.",
or_f4:"Pequeño y encantador vivero que combina lo rural, lo botánico y lo artesanal. Ideal para una pausa tranquila tras recorrer talleres y restaurantes, y para llevarse un recuerdo vivo de Pomaire.",
free_tour_label:"💡 Recorrido libre · explora a tu ritmo",
filter_lodging:"Dormir", filter_highlight:"Qué ver", route_oficial_name:"Ruta Oficial", route_oficial_meta:"5 paradas · día completo"
});
Object.assign(LANGS.es, { hs_heritage:"Tradición alfarera centenaria", hs_distance:"A 50 min de Santiago", hs_artisans:"Artesanos trabajando en vivo", hs_food:"Empanadas gigantes" });
Object.assign(LANGS.es, { mfb_text:'Conoce <strong>El Chancho alcancía de greda más grande del mundo</strong>', mfb_go:'Ver página →' });
Object.assign(LANGS.es, { fpb_tag:'💎 Imperdible', fpb_text:'El chancho alcancía de greda <strong>más grande del mundo</strong>', fpb_cta:'Conócelo →', fpb_close:'Cerrar' });
Object.assign(LANGS.es, {
nav_gruas:"Grúas y mecánicos",
s_gm_title:"Grúas y mecánicos", s_gm_sub:"Asistencia mecánica, grúas y servicios para tu vehículo en Pomaire y la ruta",
gm1_badge:"Mecánico · Taller", gm1_title:"Talleres mecánicos", gm1_detail:"Hay pequeños talleres en la ruta de acceso y camino a Melipilla. Para reparaciones mayores, lo más completo está en Melipilla ciudad (≈15 min en auto).", gm1_link:"📍 Buscar talleres",
gm2_badge:"Grúa · Asistencia en ruta", gm2_title:"Grúas y remolque", gm2_detail:"Para fallas o panne en la Ruta 78 (Autopista del Sol) o dentro del pueblo. Si un accidente bloquea la vía o hay personas heridas, llama primero a emergencias.", gm2_link1:"📞 Emergencias 133", gm2_link2:"📍 Buscar grúas",
gm3_badge:"Vulcanización · Neumáticos", gm3_title:"Vulcanizaciones", gm3_detail:"Para pinchazos y cambio de neumáticos. Hay vulcanizaciones en la ruta hacia Melipilla. Útil si viajas con la rueda de repuesto sin aire.", gm3_link:"📍 Buscar vulcanización",
gm4_badge:"¿Tienes una grúa o taller?", gm4_title:"Suma tu servicio aquí", gm4_detail:"Si ofreces grúa, mecánica o asistencia en ruta en Pomaire o Melipilla, publícate gratis en Pomaire 360 y aparece en esta guía para quienes lo necesiten.", gm4_link:"📣 Anúnciate",
gm5_badge:"Vulcanización · Mantenimiento", gm5_title:"Vulcanización y Mantenimiento Automotriz", gm5_detail:"Servicio de vulcanización, neumáticos y mantenimiento automotriz en San Antonio 1, Pomaire. Contacto directo por WhatsApp para consultar disponibilidad y horarios.", gm5_hours:"🕒 Miércoles 09:00-13:00 y 14:30-18:00 · Jueves y viernes 02:30-18:00 y 09:00-13:00 · Sábado 10:00-13:00 y 14:30-18:00 · Lunes 09:00-13:00 y 14:30-18:00 · Domingo cerrado", gm5_link1:"💬 WhatsApp +56 9 8547 8591", gm5_link2:"📍 Ver en mapa",
gm_note:"🛟 Información de carácter orientativo. Confirma cobertura, tarifas y horarios directamente con cada prestador antes de contratar."
});
Object.assign(LANGS.es, { nav_locomocion:"Locomoción" });
window._loadFullLangs = function() {
if (window._fullLangsLoaded) return Promise.resolve();
return new Promise(function(resolve) {
var s = document.createElement('script');
s.src = '/langs.js';
s.onload = function() { window._fullLangsLoaded = true; resolve(); };
document.head.appendChild(s);
});
};